title: Naruto JDR — Règles
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wiki.naruto-jdr.com" # the base hostname & protocol for your site, e.g. http://example.com

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Build settings
theme: minima
plugins:
